name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }} on ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        configuration: [Debug, Release]
        
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2.1.0
        
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.1.1

      - name: Configure
        run: |
          mkdir build
          cd build 
          cmake ..
    
      - name: Build
        run: cmake --build build --config Debug
      
      - name: Test
        run: cd build && ctest
