name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }} on ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-lastest, maxOS-latest]
        configuration: [Debug, Release]
        
    steps: 
      - uses: actions/checkout@v2
      
      - name: Configure
        run: |
          mkdir build
          cd build 
          cmake ..
    
      - name: Build
        run: cmake --build build --config Debug
      
      - name: Test
        run: cd build && ctest
